services:
    sonata.admin.experience:
        class: Admin\AdminBundle\Admin\ExperienceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Experience" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Experience
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
    sonata.admin.Guide:
        class: Admin\AdminBundle\Admin\GuideAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Personaliased Guide" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\PersonalizedGuide
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]
    sonata.admin.ExperienceAffectation:
        class: Admin\AdminBundle\Admin\ExperienceAffectationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Experience To Guide Affectation" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\ExperienceGuide
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]