services:
    sonata.admin.experience:
        class: Admin\AdminBundle\Admin\ExperienceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Experience" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Experience
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]