<?php

namespace Proxies\__CG__\Admin\AdminBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Experience extends \Admin\AdminBundle\Entity\Experience implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdExperience()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idExperience"];
        }
        $this->__load();
        return parent::getIdExperience();
    }

    public function setDateAdd($dateAdd)
    {
        $this->__load();
        return parent::setDateAdd($dateAdd);
    }

    public function getDateAdd()
    {
        $this->__load();
        return parent::getDateAdd();
    }

    public function setIdUser(\Admin\AdminBundle\Entity\User $idUser = NULL)
    {
        $this->__load();
        return parent::setIdUser($idUser);
    }

    public function getIdUser()
    {
        $this->__load();
        return parent::getIdUser();
    }

    public function setUseUser(\Admin\AdminBundle\Entity\User $useUser = NULL)
    {
        $this->__load();
        return parent::setUseUser($useUser);
    }

    public function getUseUser()
    {
        $this->__load();
        return parent::getUseUser();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idExperience', 'dateAdd', 'idUser', 'useUser');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}