bt_front_homepage:
    path:     /
    defaults: { _controller: BTFrontBundle:Default:index }
    
bt_front_experience:
    path:     /experience
    defaults: { _controller: BTFrontBundle:Experience:addExperience }
    
bt_front_experience_object:
    path:     /experience_details
    defaults: { _controller: BTFrontBundle:ExperienceObject:addExperienceObject }

bt_front_experience_feedback:
    path:     /experience_feedback
    defaults: { _controller: BTFrontBundle:Feedback:addFeedback }
