parameters:
#    bt_front.example.class: BT\FrontBundle\Example

services:
#    bt_front.example:
#        class: %bt_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
